FROM node:22-alpine

RUN apk add --no-cache \
  ffmpeg \
  vips-tools \
  perl

WORKDIR /app

ENV HOME=/data
ENV GALLERY_BASE_DIR=/data
ENV GALLERY_CONFIG_DIR=/data/config
ENV GALLERY_CACHE_DIR=/data
ENV GALLERY_CONFIG=/data/config/gallery.config.yml
ENV GALLERY_OPEN_BROWSER=false
ENV GALLERY_USE_NATIVE=ffprobe,ffmpeg
# Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
ENV GALLERY_WATCH_POLL_INTERVAL=300
ENV NODE_ENV=development

EXPOSE 3000 5173

CMD npm install --verbose && npm run build && node gallery.js run server
