/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Date format as in linux date command
 *   %b month name
 *   %d day of month, eg 01
 *   %m month, eg 12
 *   %Y 4 full year, eg 2025
 *   %y 2-digit year, eg 25
 *   %H hour eg 18
 *   %M minute, eg 06
 *   %S seconds, eg 45
 */
export interface FormatUtils {
  /**
   * Date format
   */
  date?: string;
  /**
   * Month year format
   */
  monthYear?: string;
  /**
   * Year format
   */
  year?: string;
  /**
   * time format
   */
  time?: string;
  /**
   * time format with hour and minute
   */
  hourMinute?: string;
  [k: string]: unknown;
}
