/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of plugin urls to load
 */
export type PluginUrls = string[];
/**
 * List of feature flags to disable. By default all features are enabled.
 *
 * The feature flags can also be disabled by query param 'disabled'
 */
export type FeatureFlags = (
  | ("serverEvents" | "events" | "edit")
  | "database"
  | "pwa"
  | ("offlineDatabase" | "worker")
  | string
)[];
/**
 * List of downloadable media sources. This list will be injected from the server
 */
export type MediaSources = {
  downloadable?: boolean;
  indexName?: string;
  [k: string]: unknown;
}[];
export type MediaViewDisableFlags = (("detail" | "map" | "similar" | "annotation" | "edit") | "nav")[];

/**
 * gallery configuration for webapp module
 */
export interface WebappConfig {
  webapp?: AppConfig;
  [k: string]: unknown;
}
/**
 * Configuration for webapp module
 */
export interface AppConfig {
  pluginManager?: PluginManager;
  disabled?: FeatureFlags;
  sources?: MediaSources;
  pages?: Pages;
  [k: string]: unknown;
}
export interface PluginManager {
  plugins?: PluginUrls;
  [k: string]: unknown;
}
/**
 * Customize pages
 */
export interface Pages {
  disabled?: (("edit" | "date" | "video" | "map" | "tag") | string)[];
  mediaView?: MediaViewPage;
  [k: string]: unknown;
}
/**
 * Customize single media view
 */
export interface MediaViewPage {
  disabled?: MediaViewDisableFlags;
  [k: string]: unknown;
}
