/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of feature flags to disable. By default all features are enabled.
 *
 * The feature flags can also be disabled by query param 'disabled'
 */
export type FeatureFlags = (("serverEvents" | "events" | "edit") | "pwa" | ("offlineDatabase" | "worker") | string)[];
