/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of plugin urls to load
 */
export type PluginUrls = string[];

export interface PluginManager {
  plugins?: PluginUrls;
  [k: string]: unknown;
}
