/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of downloadable media sources. This list will be injected from the server
 */
export type MediaSources = {
  downloadable?: boolean;
  indexName?: string;
  [k: string]: unknown;
}[];
